# Numpy

In [1]:
import numpy as np

### Creating Arrays

In [2]:
a = np.array([1, 2, 3]) 
b = np.array([[1.5, 2, 3], [4, 5, 6]], dtype=float) 

In [3]:
print(a)
print(b)

[1 2 3]
[[1.5 2.  3. ]
 [4.  5.  6. ]]


### Numpy Array Indexing

In [4]:
print(b[0, 2])  # arr[x, y] x = rows, y = columns
print(b[1, 1:])
print(b[:1, 1])

3.0
[5. 6.]
[2.]


### Special Initializations

In [5]:
print(np.zeros(3))  # (1 * 3) zero matrix
print(np.zeros((3, 4)))  # (3 * 4) zero matrix

[0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
print(np.ones((2, 3), dtype=np.int16))  # (2 * 3) ones matrix

[[1 1 1]
 [1 1 1]]


In [7]:
print(np.arange(10, 25, 5))  # evenly spaced values (step value=5)

[10 15 20]


In [8]:
print(np.linspace(0, 2, 9))  # evenly spaced values (number of samples=9)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [9]:
print(np.full((2, 2), 7))  # (2 * 2) constant array with the value 7

[[7 7]
 [7 7]]


In [10]:
print(np.eye(1), "\n")  # (1 * 1) identity matrix
print(np.eye(2), "\n")  # (2 * 2) identity matrix
print(np.eye(3), "\n")  # (3 * 3) identity matrix

[[1.]] 

[[1. 0.]
 [0. 1.]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 



In [11]:
print(np.random.random((3, 2)))  # (3 * 2) matrix with random values

[[0.73631004 0.09024671]
 [0.3103695  0.72664141]
 [0.8920453  0.12817865]]


In [12]:
print(np.empty((3, 2)))  # (3 * 2) matrix without initializing entries

[[0.73631004 0.09024671]
 [0.3103695  0.72664141]
 [0.8920453  0.12817865]]


### Array Inspection

In [13]:
print(b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [14]:
print(b.shape)  # dimensions (row, column) of the array

(2, 3)


In [15]:
print(len(b))  # length of the array (row number)

2


In [16]:
print(b.ndim)  # number of array dimensions (1d, 2d, 3d,...)

2


In [17]:
print(b.size)  # number of total elements in the array

6


In [18]:
print(b.dtype)  # data type of the array elements

float64


In [19]:
print(b.astype(int))  # convert an array to a different data type

[[1 2 3]
 [4 5 6]]


### Data Types 

In [20]:
np.int64  # Signed 64-bit integer types
np.float32  # Standard double-precision floating point
np.complex  # Complex numbers represented by 128 floats
np.bool  # Boolean type storing TRUE and FALSE values
np.object  # Python object type
np.string_  # Fixed-length string type
np.unicode_  # Fixed-length unicode type

numpy.str_

### Arithmetic Operations

In [21]:
print(a)
print(b)

[1 2 3]
[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [22]:
print(a - b)  # subtraction
print(np.subtract(a, b))  # subtraction with numpy method

[[-0.5  0.   0. ]
 [-3.  -3.  -3. ]]
[[-0.5  0.   0. ]
 [-3.  -3.  -3. ]]


In [23]:
print(a + b)  # addition
print(np.add(a, b))  # addition with numpy method

[[2.5 4.  6. ]
 [5.  7.  9. ]]
[[2.5 4.  6. ]
 [5.  7.  9. ]]


In [24]:
print(a / b)  # division
print(np.divide(a, b))  # division with numpy method

[[0.66666667 1.         1.        ]
 [0.25       0.4        0.5       ]]
[[0.66666667 1.         1.        ]
 [0.25       0.4        0.5       ]]


In [25]:
print(a * b)  # multiplication
print(np.multiply(a, b))  # multiplication with numpy method

[[ 1.5  4.   9. ]
 [ 4.  10.  18. ]]
[[ 1.5  4.   9. ]
 [ 4.  10.  18. ]]


In [26]:
print(np.exp(b))  # exponentiation

[[  4.48168907   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


In [27]:
print(np.sqrt(b))  # square root

[[1.22474487 1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [28]:
print(np.sin(b))  # sines of an array£

[[ 0.99749499  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]


In [29]:
print(np.cos(b))  # element-wise cosine

[[ 0.0707372  -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]


In [30]:
print(np.log(b))  # element-wise natural logarithm

[[0.40546511 0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]


In [31]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8], [9, 10], [11, 12]])
print(x.dot(y))  # dot product of x with y

[[ 58  64]
 [139 154]]


### Comparison

In [32]:
print(a == b)  # element-wise comparison

[[False  True  True]
 [False False False]]


In [33]:
print(a)
print(a < 2)  # element-wise comparison ("< 2" for every element in a)

[1 2 3]
[ True False False]


In [34]:
print(np.array_equal(a, b))  # array-wise comparison

False


### Aggregate Functions

In [35]:
print(a)

[1 2 3]


In [36]:
a.sum()  # array-wise summation

6

In [37]:
a.min()  # array-wise minimum

1

In [38]:
a.max()  # array-wise maximum

3

In [39]:
d = np.array([[1.5, 7, 2], [4, 3, 6]], dtype=float)
print(d)
print(d.max(axis=0))  # maximum value of every column 
print(d.max(axis=1))  # maximum value of every row

[[1.5 7.  2. ]
 [4.  3.  6. ]]
[4. 7. 6.]
[7. 6.]


In [40]:
print(d.cumsum(axis=1))  # cumulative sum of the elements of every row
# [[1.5, 1.5+7, 1.5+7+2]
#  [4,   4+3,    4+3+6]]

[[ 1.5  8.5 10.5]
 [ 4.   7.  13. ]]


In [41]:
a.mean()  # mean of the array

2.0

In [42]:
np.median(b)  # median of the array

3.5

In [43]:
np.corrcoef(a)  # correlation coefficient

1.0

In [44]:
np.std(b)  # standard deviation

1.5920810978785667

### Copying Array

In [45]:
h = a.view()  # create a view of the array with the same data
print(h)

[1 2 3]


In [46]:
print(np.copy(a))  # create a copy of the array

[1 2 3]


In [47]:
h = a.copy()  # create a deep copy of the array
print(h)

[1 2 3]


Copy and View Difference:


*   Any changes to the original array will not affect the copy() array.
*   Any changes to original array will directly affect the view() array.
*   Array with copy() owns the data, but view() does not!  









In [48]:
# Check if array owns it's data
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)  # copy returns None
print(y.base)  # view returns the original array

None
[1 2 3 4 5]


### Sorting Array

In [49]:
e = np.array([[4, 1, 7], [2, 8, 6]])
print(e)
f = np.copy(e)

[[4 1 7]
 [2 8 6]]


In [50]:
f.sort(axis=0)  # sort columns of the array
print(f)

[[2 1 6]
 [4 8 7]]


In [51]:
e.sort(axis=1)  # sort rows of the array
print(e)

[[1 4 7]
 [2 6 8]]


Axes in Numpy Array


*   axis 0 = y axis (vertical)
*   axis 1 = x axis (horizontal)



### Subsetting, Slicing, Indexing




In [52]:
print(a)
a[2]  # element at the 2nd index

[1 2 3]


3

In [53]:
print(b)
print(b[1, 2])  # element at row 1 column 2 (b[1][2])

[[1.5 2.  3. ]
 [4.  5.  6. ]]
6.0


In [54]:
print(b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [55]:
print(a[0:2])  # select items from index 0 to index 2 (index 2 excluded)

[1 2]


In [56]:
print(b[0:2, 1])  # select items at row 0 and row 1 in column 1 

[2. 5.]


In [57]:
print(b[:1])  # select items at row 0

[[1.5 2.  3. ]]


In [58]:
print(a[ : :-1])  # reversed array of [1, 2, 3] ==> [3, 2, 1]

[3 2 1]


In [59]:
# boolean indexing
print(a[a < 2])  # select elements that are less than 2 

[1]


### Array Manipulation

In [60]:
# Transposing Array
print(b, "\n")
i = np.transpose(b)  # permutate array dimensions (2, 3) -> (3, 2)
print(i)

[[1.5 2.  3. ]
 [4.  5.  6. ]] 

[[1.5 4. ]
 [2.  5. ]
 [3.  6. ]]


In [61]:
# Changing Array Shape
print(b.ravel())  # flatten the array
print(b)
print(b.reshape(3, 2))  # reshape, but don't change the data

[1.5 2.  3.  4.  5.  6. ]
[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[1.5 2. ]
 [3.  4. ]
 [5.  6. ]]


In [62]:
# Adding/Removing Elements
t = h.copy()
print(t)
t.resize((2, 6))  # returns a new array with shape (2, 6)
print(t)

[1 2 3]
[[1 2 3 0 0 0]
 [0 0 0 0 0 0]]


In [63]:
# Adding/Removing Elements
print(h)
print(b)
print(np.append(h, b))  # append items to an array

[1 2 3]
[[1.5 2.  3. ]
 [4.  5.  6. ]]
[1.  2.  3.  1.5 2.  3.  4.  5.  6. ]


In [64]:
# Adding/Removing Elements
print(np.insert(a, 1, 5))  # insert items to an array
print(a)
print(np.delete(a, [1]))  # deletes the item at index 1 (which is 2)

[1 5 2 3]
[1 2 3]
[1 3]


In [65]:
# Combining Arrays
print(a)
r = np.arange(10, 25, 5)
print(np.concatenate((a, r), axis=0))  # concatenate arrays

[1 2 3]
[ 1  2  3 10 15 20]


In [66]:
# Combining Arrays
print(a, "\n")
print(b, "\n")
print(np.vstack((a, b)))  # stack arrays vertically (row-wise)

[1 2 3] 

[[1.5 2.  3. ]
 [4.  5.  6. ]] 

[[1.  2.  3. ]
 [1.5 2.  3. ]
 [4.  5.  6. ]]


In [67]:
# Combining Arrays
print(e, "\n")
print(f, "\n")
print(np.hstack((e,f)))  # stack arrays horizontally (column-wise)

[[1 4 7]
 [2 6 8]] 

[[2 1 6]
 [4 8 7]] 

[[1 4 7 2 1 6]
 [2 6 8 4 8 7]]


In [68]:
# Combining Arrays
print(a, "\n")
print(r, "\n")
print(np.column_stack((a, r)))  # create stacked column-wise array

[1 2 3] 

[10 15 20] 

[[ 1 10]
 [ 2 15]
 [ 3 20]]


In [69]:
# Spliting Arrays
print(a)
print(np.hsplit(a, 3))  # split array horizontally at the 3rd index

[1 2 3]
[array([1]), array([2]), array([3])]


In [70]:
# Splitting Arrays
print(b, "\n")
print(np.vsplit(b, 2))  # split array vertically at the 2nd index

[[1.5 2.  3. ]
 [4.  5.  6. ]] 

[array([[1.5, 2. , 3. ]]), array([[4., 5., 6.]])]
